EmployeeDAA.Web/Models/ErrorViewModel.cs
namespace EmployeeDAA.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeDAA.Web/Controllers/Department/DepartmentController.cs
using DocumentFormat.OpenXml.Math;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Department
{
    [Route("Department/{action}")]
    public class DepartmentController : Controller
    {
        public const string BasePath = "~/Views/Department/";
        public IActionResult Index()
        {
            return View(BasePath + "Department.cshtml");
        }
        public IActionResult ManageDepartment()
        {
            return View(BasePath + "ManageDepartment.cshtml");
        }
    }
}

EmployeeDAA.Web/Controllers/HomeController.cs
using EmployeeDAA.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeDAA.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeDAA.Web/Controllers/Login/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Login
{
    public class LoginController : Controller
    {
        public IActionResult Custom()
        {
            return View();
        }
    }
}

EmployeeDAA.Web/Controllers/Logout/LogoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Logout
{
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EmployeeDAA.Web/Controllers/Masters/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Masters
{
    [Route("Category/{action}")]

    public class CategoryController : Controller
    {

        public const string BasePath = "~/Views/Masters/";
        public IActionResult Index()
        {
            return View(BasePath + "Category.cshtml");
        }
        public IActionResult ManageCategory()
        {
            return View(BasePath + "ManageCategory.cshtml");
        }
    }
}

EmployeeDAA.Web/Controllers/Masters/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Masters
{
    [Route("Employee/{action}")]

    public class EmployeeController : Controller
    {
        public const string BasePath = "~/Views/Masters/";
        public IActionResult Index()
        {
            return View(BasePath + "Employee.cshtml");
        }
        public IActionResult ManageEmployee()
        {
            return View(BasePath + "ManageEmployee.cshtml");
        }
    }
}

EmployeeDAA.Web/Controllers/Masters/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Masters
{
    [Route("Product/{action}")]

    public class ProductController : Controller
    {
        public const string BasePath = "~/Views/Masters/";

        public IActionResult Index()
        {
            return View(BasePath + "Product.cshtml");
        }
        public IActionResult ManageProduct()
        {
            return View(BasePath + "ManageProduct.cshtml");
        }

    }
}

EmployeeDAA.Web/Controllers/Masters/RoleController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Masters
{
   [Route("Role/{action}")]
    public class RoleController : Controller
    {
        public const string BasePath = "~/Views/Users/";
        public IActionResult Index()
        {
            return View(BasePath + "Role.cshtml");
        }
        public IActionResult ManageRole()
        {
            return View(BasePath + "ManageRole.cshtml");
        }
    }

}

EmployeeDAA.Web/Controllers/Masters/UserController.cs
using DocumentFormat.OpenXml.Drawing;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Masters
{
    [Route("User/{action}")]
    public class UserController : Controller
    {
        public const string BasePath = "~/Views/Users/";

        public IActionResult Index()
        {
            return View(BasePath + "User.cshtml");
        }
        public IActionResult ManageUsers()
        {
            return View(BasePath + "ManageUser.cshtml");
        }
        public IActionResult Profile()
        {
            return View(BasePath + "Profile.cshtml");
        }
    }
}

EmployeeDAA.Web/Controllers/Order/OrderInfoController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Order
{
    [Route("Order/{action}")]

    public class OrderInfoController : Controller
    {
        public const string BasePath = "~/Views/Order/";

        public IActionResult Index()
        {
            return View(BasePath + "OrderInfo.cshtml");
        }
        public IActionResult ManageOrderInfo()
        {
            return View(BasePath + "ManageOrderInfo.cshtml");
        }
        public IActionResult Order()
        {
            return View(BasePath + "Order.cshtml");
        }
        public IActionResult ManageOrder()
        {
            return View(BasePath + "ManageOrder.cshtml");
        }
    }
}

EmployeeDAA.Web/Controllers/Permission/PermissionController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Permission
{
    [Route("Permission/{action}")]
    public class PermissionController : Controller
    {
        public const string BasePath = "~/Views/Permission/";

        #region :: Permission ::
        public IActionResult Permission()
        {
            return View(BasePath + "Permission.cshtml");
        }
        #endregion
    }
}

EmployeeDAA.Web/Controllers/Users/ChangePasswordController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeDAA.Web.Controllers.Users
{
    [Route("User/{action}")]
    public class ChangePasswordController : Controller
    {
        public const string BasePath = "~/Views/Users/";
        public IActionResult ChangePassword()
        {
            return View(BasePath + "ChangePassword.cshtml");
        }
    }
}

EmployeeDAA.Web/Views/Department/Department.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section filters{
    <div class="form-group">
        <label>Department Name</label>
        <input type="text" class="form-control filter-control" colName="DepartmentName" option-type="input" option-op="Contains" maxlength="50">
    </div>
    <div class="form-group">
        <label>Department Code</label>
        <input type="number" class="form-control filter-control" colName="DepartmentCode" option-type="input" option-op="Contains" maxlength="50">
    </div>
}
<partial name="~/Views/Shared/_MasterNavigation.cshtml" />

<div class="middle__bar middle__bar--has-tab">
    <partial name="~/Views/Shared/_ManageTopDataFilter.cshtml" />

    <table id="tblDepartment" class="table table-bordered table-striped checkbox__on--hover tasks w-100" role="presentation">
    </table>
</div>
<div class="modal fade" tabindex="-1" id="popmodel" role="dialog" aria-labelledby="myLargeModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content" id="popmodelcontent">
        </div>
    </div>
</div>
@section scripts{

    <script src="~/js/pages/Department/department.js" asp-append-version="true"></script>
}

EmployeeDAA.Web/Views/Department/ManageDepartment.cshtml
@{
    ViewData["Title"] = "Manage Department";
    Layout = null;
}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle">@ViewData["Title"]</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form method="post" apiurl="Department" id="frmDocumentClass" role="form">
    <div class="modal-body">
        <input type="hidden" id="Id" Name="Id" value="0" />
        <div class="form-group">
            <label>Employee Id <span class="text-danger">*</span></label>
            <input type="text" class="form-control" id="EmployeeId" name="EmployeeId" required />
        </div>
        <div class="form-group">
            <label>Department Name<span class="text-danger">*</span></label>
            <input type="text" class="form-control " id="DepartmentName" name="DepartmentName" required />
        </div>
        <div class="form-group">
            <label>Department Code <span class="text-danger">*</span></label>
            <input type="number" class="form-control numberOnly" id="DepartmentCode" name="DepartmentCode" required />
        </div>
        <div class="d-inline-block align-checklistgrpitems-center justify-content-center">
            <label>Status </label>
            <label class="switch small-switch mb-0">
                <input type="checkbox" id="IsActive" name="IsActive" class="btn-grid-isactive" value="1" checked="checked">
                <span class="switch-slider"></span>
            </label>
        </div>


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>

EmployeeDAA.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4" style="margin-top:100px">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmployeeDAA.Web/Views/Login/Custom.cshtml
@{
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Employee - HUB</title>

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/css/all.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/sweetalert2.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <div class="login__header">
        <h1 style="font-size:50px">EmployeeHUB</h1>
        <h1>HUB</h1>
    </div>
    <div class="loader-main hide-block">
        <div id="loading"></div>
    </div>
    <section class="login__wrap">
        <div class="login__box">
            <h3>Sign In</h3>
            <form method="post" apiurl="Login/Authenticate" id="frmLogin" role="form">
                <div class="form-group">
                    <label>Username</label>
                    <input class="form-control" type="text" title="Username required" name="Username" id="Username" required>
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input id="password__field" type="password" class="form-control" name="Password" title="Password required" value="" required>
                    <span toggle="#password__field" class="fa fa-fw field__icon toggle__password fa-eye"></span>
                </div>
                <div class="form-group">
                    <label>Verification Code</label>
                    <div class="form-group recaptcha">
                        <div class="captcha__img">
                            <img id="CaptchaImage" />
                            <span class="captcha__refresh fas fa-sync-alt"></span>
                        </div>
                        <input type="text" class="form-control numberRegEx" id="CaptchaCode" name="CaptchaCode"
                               placeholder="Verification Code *" maxlength="4" autocomplete="off"
                               onpaste="return false" title="Captcha code required" required>
                    </div>
                    <label id="CaptchaCode-error" class="error" for="CaptchaCode"></label>
                    <input type="hidden" id="CaptchaToken" name="CaptchaToken" />
                </div>
                <div class="form-group login__action">
                    <button type="button" id="btnLogin" class="btn btn-primary">Sign In</button>
                </div>
            </form>
        </div>
    </section>
    <!-- Main JS -->
    <script src="~/js/jquery-3.6.0.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <!-- Bootstrap JS -->
    <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
    <environment include="Development">
        <script src="~/js/Common/ConfigURL.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/Common/ConfigProd.js" asp-append-version="true"></script>
    </environment>
    <script src="~/js/Common/RequestResponse.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.all.js" asp-append-version="true"></script>
    <script src="~/js/Common/Common.js" asp-append-version="true"></script>
    <script src="~/js/pages/Login/Login.js" asp-append-version="true"></script>
</body>
</html>

EmployeeDAA.Web/Views/Logout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Employee - HUB</title>

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/css/all.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/sweetalert2.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <div class="login__header">
        <h1 style="font-size:50px">EmployeeHUB</h1>
        <h1>HUB</h1>
    </div>
    <div class="loader-main hide-block">
        <div id="loading"></div>
    </div>
    <div class="login__wrap">
        <div class="login__box">
            <h3 class="text-center">You have successfully logged out from this application.</h3>
            <div class="form-group login__action">
                <a href="~/Login/Custom" class="btn btn-primary">Login</a>
            </div>
        </div>
    </div>

    <script src="~/js/jquery-3.6.0.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <!-- Bootstrap JS -->
    <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
    <environment include="Development">
        <script src="~/js/Common/ConfigURL.js" asp-append-version="true"></script>
    </environment>
    <script src="~/js/Common/RequestResponse.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.all.js" asp-append-version="true"></script>
    <script src="~/js/Common/Common.js" asp-append-version="true"></script>

   
</body>
</html>

EmployeeDAA.Web/Views/Masters/Category.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section filters{
    <div class="form-group">
        <label>Category Name</label>
        <input type="text" class="form-control filter-control" colName="CategoryName" option-type="input" option-op="Contains" maxlength="50">
        <span class="field__clear d-none"><em class="fas fa-times"></em></span>
    </div>
    <div class="form-group">
        <label>SortOrder</label>
        <input type="text" class="form-control numberOnly filter-control" colName="SortOrder" option-type="input" option-op="Equals" maxlength="3">
        <span class="field__clear d-none"><em class="fas fa-times"></em></span>
    </div>
}
<partial name="~/Views/Shared/_MasterNavigation.cshtml" />

<div class="middle__bar middle__bar--has-tab">
    <partial name="~/Views/Shared/_ManageTopDataFilter.cshtml" />

    <table id="tblEmployee" class="table table-bordered table-striped checkbox__on--hover tasks w-100" role="presentation">
    </table>
</div>
<div class="modal fade" tabindex="-1" id="popmodel" role="dialog" aria-labelledby="myLargeModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content" id="popmodelcontent">
        </div>
    </div>
</div>
@section scripts{

    <script src="~/js/pages/category/categorymaster.js" asp-append-version="true"></script>
}

EmployeeDAA.Web/Views/Order/ManageOrder.cshtml
@{
    ViewData["Title"] = "Manage Document Type";
    Layout = null;
}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle">Manage Product</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <table id="tblProduct" class="table table-bordered table-striped checkbox__on--hover tasks w-100" role="presentation">
    </table>
    <button type="button" class="btn btn-success" id="submitButton" style="display: none;">Submit</button>

</div>

EmployeeDAA.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeHUB.Web</title>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <environment include="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/bootstrap-select.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/bootstrap-datetimepicker.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/bootstrap-side-modals.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/datatables.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/responsive.dataTables.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/fixedColumns.dataTables.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/all.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/sweetalert2.css" asp-append-version="true" />
        <script src="~/js/jquery-3.6.0.min.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/bootstrap-select.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/bootstrap-datetimepicker.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/bootstrap-side-modals.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/datatables.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/responsive.dataTables.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/fixedColumns.dataTables.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/all.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/sweetalert2.css" asp-append-version="true" />
        <script src="~/js/jquery-3.6.0.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <div class="loader-main hide-block">
        <div id="loading"></div>
    </div>
    <header>
        <div class="container-fluid">
            <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">EmployeeHUB.Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                <div class="nav-wrap">
                    <nav class="greedy-nav d-none">
                        <div class="mobile_menu_view"></div>
                        <ul class="visible-links">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Employee" asp-action="index">Employee</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Department" asp-action="index">Department</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Category" asp-action="index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Role" asp-action="index">Role</a>
                            </li>
@*                             <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="OrderInfo" asp-action="index">Order Registration</a>
                            </li>
 *@                            
                            <li class="nav-item">
                                <a pagecode='Permission' href="~/Permission/Permission"><i class="fas fa-question"></i> Roles & Permissions</a>
                            </li>
                        </ul>

                    </nav>
                </div>

            </div>
            <div class="header__right">

                <div class="userdrop__box">
                    <span class="userdrop__icon"></span>

                    <div class="btn-group">
                        <button class="btn btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span id="GlbUserName"></span></button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="~/User/Profile"><i class="fas fa-user"></i> Profile</a>
                            <a class="dropdown-item" href="~/User/ChangePassword"><i class="fas fa-key"></i> Change Password</a>
                            <a class="dropdown-item NoBind" id="Logout"><i class="fas fa-sign-out-alt"></i> Logout</a>
                        </div>
                    </div>
                </div>
            </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div id="filtersbar" class="filtersbar">
        <div class="filtersheader">
            <span><i class="fas fa-filter"></i> <strong>Filters</strong></span>
            <a class="filtersbar__close"><em class="fas fa-times"></em></a>
        </div>
        <div id="divfilter" class="filtersbody">
            <div id="filterctrl">
                @RenderSection("filters", required: false)
            </div>
            <div class="form-group text-right">
                <button id="btnfilterclear" type="button" class="btn btn-sm btn-secondary mr-1">Clear All</button>
                <button id="btnFilter" class="btn btn btn-primary btn-sm filtersbar__close">Search</button>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EmployeeHUB.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/js/popper.min.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap-select.min.js" asp-append-version="true"></script>
        <script src="~/js/moment.min.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap-datetimepicker.min.js" asp-append-version="true"></script>
        <script src="~/js/datatables.min.js" asp-append-version="true"></script>
        <script src="~/js/dataTables.responsive.min.js" asp-append-version="true"></script>
        <script src="~/js/dataTables.fixedColumns.min.js" asp-append-version="true"></script>
        <script src="~/js/timepicki.js" asp-append-version="true"></script>
        <script src="~/js/Common/custom.js" asp-append-version="true"></script>
        <script src="~/js/Common/ConfigURL.js" asp-append-version="true"></script>
        <script src="~/js/Common/RequestResponse.js" asp-append-version="true"></script>
        <script src="~/js/Controls/DataTableFilter.js" asp-append-version="true"></script>
        <script src="~/js/Controls/DataTableConfig.js" asp-append-version="true"></script>
        <script src="~/js/Controls/DropDownConfig.js" asp-append-version="true"></script>
        <script src="~/js/tag-input.js" asp-append-version="true"></script>
        <script src="~/js/Common/Common.js" asp-append-version="true"></script>
        <script src="~/js/Pages/layout.js" asp-append-version="true"></script>
        <script src="~/js/Pages/comments.js" asp-append-version="true"></script>
        <script src="~/js/sweetalert2.all.js" asp-append-version="true"></script>
        <script src="~/js/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/js/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>


    </environment>
    <environment exclude="Development">
        <script src="~/js/popper.min.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap-select.min.js" asp-append-version="true"></script>
        <script src="~/js/moment.min.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap-datetimepicker.min.js" asp-append-version="true"></script>
        <script src="~/js/datatables.min.js" asp-append-version="true"></script>
        <script src="~/js/dataTables.responsive.min.js" asp-append-version="true"></script>
        <script src="~/js/dataTables.fixedColumns.min.js" asp-append-version="true"></script>
        <script src="~/js/timepicki.js" asp-append-version="true"></script>
        <script src="~/js/Common/custom.js" asp-append-version="true"></script>
        <script src="~/js/Common/ConfigProd.js" asp-append-version="true"></script>
        <script src="~/js/Common/RequestResponse.js" asp-append-version="true"></script>
        <script src="~/js/Controls/DataTableFilter.js" asp-append-version="true"></script>
        <script src="~/js/Controls/DataTableConfig.js" asp-append-version="true"></script>
        <script src="~/js/Controls/DropDownConfig.js" asp-append-version="true"></script>
        <script src="~/js/tag-input.js" asp-append-version="true"></script>
        <script src="~/js/Common/Common.js" asp-append-version="true"></script>
        <script src="~/js/Pages/layout.js" asp-append-version="true"></script>
        <script src="~/js/Pages/comments.js" asp-append-version="true"></script>
        <script src="~/js/sweetalert2.all.js" asp-append-version="true"></script>
        <script src="~/js/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/js/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    </environment>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>